version: "2"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: faxtu_postgres
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:35432:5432"
  redis:
    image: redis:3.2-alpine
    container_name: faxtu_redis
    ports:
      - "127.0.0.1:36379:6379"
